# .slather.yml

ci_service: travis_ci
coverage_service: coveralls
xcodeproj: Example/UITableViewWrapper.xcodeproj
workspace: Example/UITableViewWrapper.xcworkspace
scheme: UITableViewWrapper-Example
source_directory: UITableViewWrapper/Classes
# binary_basename: SnackBar
ignore:	
  - ExamplePodCode/*
  - ProjectTestsGroup/*
